"""Document assembly: build(), layer gating, artifact folding, CLI entrypoint."""

from __future__ import annotations

import json
import csv
import argparse
from pathlib import Path

from report.components.badges import _CONFLICT, _STRENGTH, _source_class_badges, _source_identity_badges
from report.components.base import _ANCHORS, _EMITTED_CLAIM_TARGETS, _fmt_datetime_html, _md_block, e, refs, text_refs
from report.components.bib import _format_apa_html, _parse_bibtex
from report.components.icons import _logo_svg
from report.layers.argument_map import _argument_map_interactive_html
from report.layers.claims import _claims_table_html
from report.layers.deliberation import _claim_effects_from_deliberation, _cx_detail_html, _deliberation_html, _resolution_plan_inner, _run_manifest_html
from report.layers.evidence import _evidence_table_html
from report.layers.lenses import _evidence_plan_html, _lens_charters_html, _lens_snapshot_html


CSS = (Path(__file__).resolve().parent.parent / "styles.css").read_text(encoding="utf-8")


from report.thresholds import STATUS_CLASS as _STATUS_CLASS, score_class as _score_cls


_LAYERS = ("brief", "report", "appendix", "all")


def _layer_visible(layer: str, tier: str) -> bool:
    """Which section tiers render for a given output layer.

    ``all`` renders everything (byte-identical to the historic single file);
    ``report`` is the curated brief plus its analytical backbone; ``appendix``
    is the raw-artifact / heavy-interactive dump on its own."""
    if layer == "all":
        return True
    if layer == "brief":
        return tier == "brief"
    if layer == "report":
        return tier in ("brief", "report")
    if layer == "appendix":
        return tier == "appendix"
    return True


def _provenance_html(p) -> str:
    """Render the tamper-evident provenance seal (07a) in the appendix,
    structurally mirroring the run-manifest table.

    INTEGRITY, not authenticity: the disclaimer copy states that content hashes
    prove the bundle is unchanged since sealing, not *who* sealed it, and that an
    unsigned manifest can be regenerated by anyone with write access. The full
    per-file hash list lives in a collapsed <details> block, never the visible
    table."""
    if not isinstance(p, dict) or not p:
        return ""
    rows = ""

    def _row(label, val_html):
        return f'<tr><th scope="row">{e(label)}</th><td>{val_html}</td></tr>'

    if p.get("sealed_at"):
        rows += _row("Sealed", _fmt_datetime_html(str(p["sealed_at"])))
    verdict = p.get("verdict_at_seal_time")
    if isinstance(verdict, dict) and verdict.get("status"):
        rows += _row("Verdict at seal time", e(str(verdict["status"])))
    if p.get("hash_algorithm"):
        rows += _row("Hash algorithm", e(str(p["hash_algorithm"])))
    artifacts = p.get("artifacts") if isinstance(p.get("artifacts"), list) else []
    rows += _row("Artifacts sealed", e(str(len(artifacts))))
    if p.get("schema_version"):
        rows += _row("Schema version", e(str(p["schema_version"])))
    if p.get("generator_version"):
        rows += _row("Generator version", e(str(p["generator_version"])))
    note = ('<p class="lead">These content hashes prove the bundle is '
            '<b>unchanged since it was sealed</b> — they establish '
            '<b>integrity, not authenticity</b>. An unsigned manifest cannot prove '
            '<i>who</i> sealed it, and anyone with write access can alter a file and '
            'regenerate the manifest to match. A matching seal supports — it does '
            'not replace — your own chain-of-custody controls when provenance '
            'matters in a legal or regulatory context.</p>')
    detail = ""
    if artifacts:
        items = "".join(
            '<li><span class="sid">%s</span> <code>%s</code>%s</li>' % (
                e(str(a.get("path", ""))),
                e(str(a.get("sha256", ""))),
                (f' <span class="ty">· {e(str(a.get("bytes")))} bytes</span>'
                 if a.get("bytes") is not None else ""))
            for a in artifacts if isinstance(a, dict))
        detail = ('<details class="bibtex-detail"><summary>Sealed artifact hashes (%d)'
                  '</summary><ul class="src">%s</ul></details>' % (len(artifacts), items))
    return f'{note}<table class="manifest-table"><tbody>{rows}</tbody></table>{detail}'


# 07b: badge tone per change_class. Reuses the EXISTING severity palette (no new
# color token) so a reader's learned color-vocabulary still applies: open=red
# (retracted/unavailable), part=amber (superseded/corrected), done=calm (unchanged),
# kind=neutral (not_rechecked — the honest-uncertainty state, never green/red).
_REFRESH_BADGE = {
    "retracted": ("open", "retracted"),
    "unavailable": ("open", "unavailable"),
    "superseded": ("part", "superseded"),
    "corrected": ("part", "corrected"),
    "unchanged": ("done", "unchanged"),
    "not_rechecked": ("kind", "not re-checked"),
}


def _refresh_diff_html(diff: dict) -> dict:
    """Build the three-tier "What changed since" panel bodies from refresh_diff.json.

    Returns {brief, report, appendix} HTML fragments. Honesty rules enforced in the
    builder, not just copy (07b §9/§10): `not_rechecked` rows never render a
    confirmation tone; the one-line summary is computed from the JSON counts (never
    hand-typed prose that could drift); the language is retrospective ("since"),
    never "monitoring"/"live"."""
    if not isinstance(diff, dict):
        return {"brief": "", "report": "", "appendix": ""}
    rc = diff.get("recheck") or {}
    changes = diff.get("source_changes") or []

    tally: dict = {}
    for row in changes:
        cc = row.get("change_class")
        tally[cc] = tally.get(cc, 0) + 1
    parts = []
    for key, label in (("retracted", "retraction(s) detected"),
                       ("superseded", "superseded"), ("corrected", "corrected"),
                       ("unavailable", "no longer available"),
                       ("unchanged", "re-resolved clean"),
                       ("not_rechecked", "could not be re-verified")):
        if tally.get(key):
            parts.append(f"{tally[key]} {label}")
    considered = rc.get("sources_considered", len(changes))
    rechecked = rc.get("sources_rechecked", 0)
    summary = (f"{rechecked} of {considered} sources re-checked"
               + (" (offline — cache only)" if rc.get("offline") else "")
               + " — " + ("; ".join(parts) if parts else "no sources to re-check") + ".")

    gb = (diff.get("gate_before") or {}).get("status") or "?"
    ga = (diff.get("gate_after") or {}).get("status") or "?"
    if diff.get("gate_changed"):
        gate_line = (f'<p class="lead"><b>Quality gate moved: {e(gb)} → {e(ga)}.</b> '
                     'Re-read the review verdict below.</p>')
    else:
        gate_line = f'<p class="lead">Quality gate did not move ({e(ga)}).</p>'

    as_of = rc.get("as_of")
    stamp = f'<p class="lead">Re-checked as of {e(as_of)}.</p>' if as_of else ""
    brief = f'{stamp}<p class="lead">{e(summary)}</p>{gate_line}'

    # Report tier — per-claim and per-contradiction effects.
    report_bits = ""
    claim_changes = diff.get("claim_changes") or []
    if claim_changes:
        items = ""
        for cc in claim_changes:
            srcs = ", ".join(cc.get("source_ids") or [])
            items += ('<li>%s <b>%s</b> — <span class="mono">%s</span> (%s)</li>' % (
                refs([cc.get("claim_id")]) if cc.get("claim_id") else "",
                e(cc.get("direction", "")), e(cc.get("rule", "")), e(srcs)))
        report_bits += ('<p class="lead"><b>Claim effects</b></p>'
                        f'<ul class="clean">{items}</ul>')
    cx_changes = [x for x in (diff.get("contradiction_changes") or [])
                  if "changed class" in str(x.get("reason", ""))]
    if cx_changes:
        items = "".join(
            '<li>%s %s → %s — %s</li>' % (
                refs([x.get("id")]) if x.get("id") else "",
                e(x.get("status_before", "")), e(x.get("status_after", "")), e(x.get("reason", "")))
            for x in cx_changes)
        report_bits += ('<p class="lead"><b>Contradictions touched</b></p>'
                        f'<ul class="clean">{items}</ul>')

    # Appendix tier — full per-source table (every row, never truncated).
    rows = ""
    for row in changes:
        cc = row.get("change_class", "")
        tone, label = _REFRESH_BADGE.get(cc, ("kind", cc or "—"))
        via = ", ".join(row.get("detected_via") or []) or "—"
        bstat = row.get("before_status") or "—"
        astat = row.get("after_status") or "—"
        rows += ('<tr><td class="mono">%s</td><td><span class="tag %s">%s</span></td>'
                 '<td>%s → %s</td><td class="mono">%s</td><td>%s</td></tr>' % (
                     e(row.get("source_id", "")), tone, e(label),
                     e(bstat), e(astat), e(via), e(row.get("detail", ""))))
    appendix = ('<table><thead><tr><th>Source</th><th>Change</th><th>Status</th>'
                '<th>Detected via</th><th>Detail</th></tr></thead>'
                f'<tbody>{rows}</tbody></table>') if rows else ""

    tw = diff.get("tripwires_evaluated")
    if isinstance(tw, list) and tw:
        items = "".join(
            '<li>%s monitoring %s — %s</li>' % (
                e(str(t.get("id", ""))), e(str(t.get("monitoring_source", ""))), e(str(t.get("note", ""))))
            for t in tw)
        appendix += f'<p class="lead"><b>Tripwires evaluated</b></p><ul class="clean">{items}</ul>'
    pivotal = diff.get("pivotal_claims_touched")
    if isinstance(pivotal, list) and pivotal:
        appendix += ('<p class="lead"><b>Pivotal claims touched:</b> '
                     + ", ".join(e(str(p)) for p in pivotal) + "</p>")

    return {"brief": brief, "report": report_bits, "appendix": appendix}


def _tripwire_sort_key(tw: dict):
    cost_order = {"high": 0, "medium": 1, "low": 2}
    return (cost_order.get(str(tw.get("reversal_cost") or "").lower(), 3),
            str(tw.get("id") or ""))


def _tripwire_monitor_badge(kind) -> str:
    if kind == "auto_recheckable":
        return '<span class="tag kind">auto</span>'
    if kind == "manual_watch":
        return '<span class="tag part">manual</span>'
    return f'<span class="tag kind">{e(kind or "unknown")}</span>'


_ARG_SUPPORT_BADGE = {
    "passage_checked": ("done", "passage-checked"),
    "partial_review": ("part", "partial/review"),
    "metadata_only": ("kind", "metadata only"),
    "not_checked": ("kind", "not checked"),
}


def _argument_support_row_status(packet: dict, verdict: dict | None) -> tuple[str, str]:
    access = str(packet.get("source_access") or "").lower()
    if access == "metadata_only":
        return ("kind", "metadata only")
    if (access == "full_text" and isinstance(verdict, dict)
            and str(verdict.get("verdict") or "").lower() == "entails"
            and str(verdict.get("scope_preserved") or "").lower() == "yes"):
        return ("done", "passage-checked")
    return ("part", "partial/review")


def _argument_support_html(review: dict, support_packets, verdicts, scores: dict) -> str:
    status = str(review.get("argument_support_status") or "").lower()
    score = scores.get("argument_support")
    if not status and score is None and not support_packets:
        return ""
    tone, label = _ARG_SUPPORT_BADGE.get(status, ("kind", status.replace("_", " ") or "not checked"))
    score_html = "" if score is None else f' <b>{e(score)}</b>/100'
    body = (
        '<p class="lead"><span class="tag %s">%s</span>%s. '
        'This score is separate from traceability: it requires a local quoted passage, '
        'a support packet, and an explicit entailment/scope verdict. It does not prove truth.</p>'
        % (tone, e(label), score_html)
    )
    if not isinstance(support_packets, list) or not support_packets:
        return body
    by_packet = {
        v.get("packet_id"): v
        for v in (verdicts or [])
        if isinstance(v, dict) and v.get("packet_id")
    }
    rows = ""
    for packet in support_packets:
        if not isinstance(packet, dict):
            continue
        pid = packet.get("packet_id") or ""
        verdict = by_packet.get(pid)
        rtone, rlabel = _argument_support_row_status(packet, verdict)
        refs_html = refs([x for x in (packet.get("claim_id"), packet.get("evidence_id"), packet.get("source_id")) if x])
        rationale = ""
        if isinstance(verdict, dict) and verdict.get("rationale"):
            rationale = f'<span class="verdict-rationale">{text_refs(verdict.get("rationale"))}</span>'
        rows += (
            '<tr id="ref-%s"><td class="mono">%s</td><td>%s</td>'
            '<td><span class="tag %s">%s</span></td><td>%s</td><td>%s%s</td></tr>'
            % (
                e(pid), e(pid), refs_html or "—", rtone, e(rlabel),
                e(packet.get("source_material_path") or "—"),
                text_refs(packet.get("quoted_passage") or "—"), rationale,
            )
        )
    if rows:
        body += (
            '<table class="support-packet-table"><thead><tr><th>Packet</th><th>Refs</th>'
            '<th>Status</th><th>Material</th><th>Quoted passage</th></tr></thead><tbody>'
            + rows + "</tbody></table>"
        )
    return body


def _tripwire_cost_chip(cost) -> str:
    tone = {"high": "open", "medium": "part", "low": "done"}.get(
        str(cost or "").lower(), "kind")
    return f'<span class="tag {tone}">{e(cost or "unknown")}</span>'


def _tripwire_anchor(tid) -> str:
    tid = str(tid or "")
    if not tid:
        return ""
    return f'<a class="cid clink" href="#ref-{e(tid)}">{e(tid)}</a>'


def _tripwires_html(tripwires) -> str:
    if not isinstance(tripwires, list) or not tripwires:
        return ""
    rows = ""
    for tw in sorted((t for t in tripwires if isinstance(t, dict)), key=_tripwire_sort_key):
        tid = str(tw.get("id") or "")
        claims = refs(tw.get("claim_ids")).strip()
        option = tw.get("option")
        watches = claims
        if option:
            option_html = f'<span class="tw-option">{e(option)}</span>'
            watches = f"{watches} {option_html}".strip()
        if not watches:
            watches = '<span class="tag kind">unbound</span>'
        monitor = _tripwire_monitor_badge(tw.get("monitor_kind"))
        if tw.get("monitoring_source"):
            monitor += f' <span class="tw-source">{text_refs(tw.get("monitoring_source"))}</span>'
        cadence = text_refs(tw.get("refresh_cadence", ""))
        cost = _tripwire_cost_chip(tw.get("reversal_cost"))
        direction = f'<span class="tw-dir">{e(tw.get("direction", ""))}</span>' if tw.get("direction") else ""
        threshold = ""
        if tw.get("threshold_or_event"):
            threshold = f'<div class="tw-threshold">{text_refs(tw.get("threshold_or_event"))}</div>'
        rows += (
            f'<tr id="ref-{e(tid)}"><td><span class="mono">{e(tid)}</span> '
            f'{text_refs(tw.get("condition", ""))}{threshold}</td>'
            f'<td>{watches}</td><td>{monitor}</td><td>{cadence}</td>'
            f'<td>{cost} {direction}</td><td>{text_refs(tw.get("action", ""))}</td></tr>'
        )
    if not rows:
        return ""
    return (
        '<table class="tripwire-table"><thead><tr><th>Condition</th><th>Watches</th>'
        '<th>Monitor</th><th>Cadence</th><th>Reversal cost</th><th>Action</th></tr>'
        f'</thead><tbody>{rows}</tbody></table>'
    )


def build(data: dict, layer: str = "all") -> str:
    if layer not in _LAYERS:
        layer = "all"
    counts = data.get("counts", {})
    st = data.get("status", {})
    scores = st.get("scores", {})
    if not scores and isinstance(data.get("review"), dict):
        scores = data["review"].get("scores", {}) or {}
    p: list[str] = []
    a = p.append

    _ANCHORS.clear()
    _EMITTED_CLAIM_TARGETS.clear()
    for s in data.get("sources", []) or []:
        if s.get("id"):
            _ANCHORS.add(s["id"])
    for c in data.get("contradictions", []) or []:
        if c.get("id"):
            _ANCHORS.add(c["id"])
    # When a claims ledger is present it owns the C-### anchor targets, so chips
    # elsewhere link to it instead of minting a duplicate id at first mention.
    for c in data.get("claims", []) or []:
        cid = c.get("claim_id") or c.get("id")
        if cid:
            _ANCHORS.add(cid)
            _EMITTED_CLAIM_TARGETS.add(cid)
    for ev in data.get("evidence", []) or []:
        eid = ev.get("evidence_id") or ev.get("id")
        if eid:
            _ANCHORS.add(eid)

    a("<!doctype html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\" />")
    a('<meta name="viewport" content="width=device-width, initial-scale=1" />')
    a(f"<title>{e(data.get('title','Storm Council report'))}</title>")
    a("<style>" + CSS + "</style>")
    if layer == "brief":
        # Print-friendly rules scoped to the standalone brief only, so the
        # default `all` output stays byte-identical to the historic report.
        a("<style>@media print{.toc{display:none!important}"
          ".page{max-width:none;padding:0}"
          "section,.fcard,.opt,.bottom-line-card{break-inside:avoid}}</style>")
    a("</head>\n<body>\n<main class=\"page\">")

    logo_svg = _logo_svg()
    a('<header class="report-header"><div class="report-title-block">')
    a(f'<p class="eyebrow">{e(data.get("eyebrow", "Storm Council · Decision Brief"))}</p>')
    a(f'<h1>{e(data.get("title",""))}</h1>')
    if data.get("subtitle"):
        a(f'<p class="subtitle">{e(data["subtitle"])}</p>')
    a("</div>")
    if logo_svg:
        a(f'<div class="brand-logo" aria-label="Storm Council icon">{logo_svg}</div>')
    a("</header>")

    meta = []
    if data.get("mode"): meta.append(f'<span><b>Mode</b> {e(data["mode"])}</span>')
    if data.get("audience"): meta.append(f'<span><b>Audience</b> {e(data["audience"])}</span>')
    if counts:
        meta.append('<span><b>Lenses</b> %s · <b>Claims</b> %s · <b>Sources</b> %s · <b>Conflicts</b> %s</span>'
                    % (e(counts.get("lenses","-")), e(counts.get("claims","-")),
                       e(counts.get("sources","-")), e(counts.get("conflicts","-"))))
    if meta:
        a('<div class="meta">' + "".join(meta) + "</div>")

    if st:
        cls = _STATUS_CLASS.get(str(st.get("level", "")).lower(), "")
        verdict = st.get("verdict", "")
        srow = ""
        if scores:
            def _verdict_badge_cls(v):
                vl = str(v).upper()
                if vl == "PASS": return "vb-pass"
                if "CAVEAT" in vl: return "vb-caveats"
                if "FAIL" in vl: return "vb-fail"
                return "vb-unknown"
            score_items = [
                (scores.get("coverage", "-"), "Coverage"),
                (scores.get("traceability", "-"), "Traceability"),
                (scores.get("argument_support", "-"), "Argument Support"),
                (scores.get("contradiction", "-"), "Contradiction"),
                (scores.get("recommendation", "-"), "Rec. Support"),
            ]
            score_html = "".join(
                '<div class="vscore %s"><span class="vscore-val">%s</span>'
                '<span class="vscore-key">%s</span></div>'
                % (_score_cls(val), e(str(val)), e(label))
                for val, label in score_items
            )
            srow = (
                '<div class="verdict-panel">'
                '<span class="verdict-panel-label">Review verdict</span>'
                '<span class="verdict-status-badge %s">%s</span>'
                '<span class="verdict-divider"></span>'
                '<div class="verdict-scores">%s</div>'
                '</div>'
                % (_verdict_badge_cls(verdict), e(verdict), score_html)
            )
        crow = ""
        checks = list(st.get("checks") or [])
        # 07a: reflect a sealed provenance bundle as one extra integrity chip.
        # The renderer never runs --check-seal itself; it only surfaces what is
        # already in `data`, so this is always the neutral "sealed" state.
        if data.get("provenance"):
            checks = checks + [{"value": "sealed", "label": "provenance", "tone": "neutral"}]
        if checks:
            chips = "".join(
                '<span class="chk %s"><b>%s</b> %s</span>' % (
                    e(str(c.get("tone", "")).lower()), e(c.get("value", "")), e(c.get("label", "")))
                for c in checks)
            crow = f'<div class="checks">{chips}</div>'
        a('<div class="status %s"><span class="pill">%s</span><b>%s</b><p>%s</p>%s%s</div>' % (
            cls, e(st.get("pill", "STATUS")), e(st.get("headline", "")), text_refs(st.get("detail", "")), crow, srow))

    howto = data.get("how_to_read") or [
        "<b>The panel is author-constructed.</b> Where the lenses agree, treat it as a strong hypothesis, not independent proof.",
        "<b>Confidence (0.0-1.0) is separate from evidence status.</b> A high-confidence forecast is still a forecast.",
        "<b>Fact, inference, and recommendation are labelled separately.</b>",
        "<b>Disagreements are kept on the record</b>, not resolved by force.",
        "<b>A Contradiction score of 50 means no contradictions were logged</b> — a neutral \"no data\" reading, not a penalty. It only drops toward 0 when logged contradictions are left unresolved.",
    ]
    a('<div class="howto"><h3>How to read this</h3><ul>' +
      "".join(f"<li>{li}</li>" for li in howto) + "</ul></div>")

    section_no = [0]
    toc_items: list = []

    def sec(title, body, tier="report", slug=None):
        if not _layer_visible(layer, tier):
            return
        section_no[0] += 1
        num = f"{section_no[0]:02d}"
        toc_items.append((num, title))
        stable_anchor = ""
        if slug:
            stable_anchor = f'<span id="sec-{e(slug)}" class="section-anchor" tabindex="-1"></span>'
        a(f'<section id="sec-{num}">{stable_anchor}<h2><span class="num">{num}</span>{e(title)}</h2>{body}</section>')

    bottom_parts = []
    if data.get("bottom_line"):
        bottom_parts.append(
            '<div class="bottom-line-card"><p>%s</p></div>' % text_refs(data["bottom_line"])
        )

    # 07c: the single load-bearing claim — rendered only when decision_criticality.json
    # named a `most_load_bearing` that resolves to a `pivotal` ranking. Absent ⇒ nothing.
    dc = data.get("decision_criticality")
    if isinstance(dc, dict) and dc.get("most_load_bearing"):
        mlb = dc.get("most_load_bearing")
        entry = next(
            (r for r in (dc.get("rankings") or [])
             if isinstance(r, dict)
             and (r.get("claim_id") == mlb or r.get("contradiction_id") == mlb)
             and str(r.get("criticality") or "").lower() == "pivotal"),
            None)
        if entry:
            rid = entry.get("claim_id") or entry.get("contradiction_id")
            claim_txt = ""
            for c in data.get("claims") or []:
                if (c.get("claim_id") or c.get("id")) == rid:
                    claim_txt = c.get("claim_text") or c.get("text") or ""
                    break
            trace = str(entry.get("rule_trace") or "").strip()
            body = ('<div class="bottom-line-card pivotal-card"><p>'
                    'If one assumption is wrong, this is the one most likely to change '
                    'the recommendation: ' + text_refs(rid))
            if claim_txt:
                body += ' — ' + text_refs(claim_txt)
            body += '.</p>'
            if trace:
                body += f'<p class="pivotal-trace">{e(trace)}</p>'
            body += '</div>'
            bottom_parts.append('<p class="sec-kicker">If this is wrong</p>' + body)

    # 07b: "What changed since" panel — rendered only when refresh_diff.json was
    # folded in. Absent ⇒ nothing (no panel, no placeholder, no "never rechecked"
    # banner: that would over-claim knowledge about a bundle this phase never touched).
    rd = data.get("refresh_diff")
    refresh_report_html = ""
    refresh_appendix_html = ""
    if isinstance(rd, dict) and rd.get("source_changes") is not None:
        panels = _refresh_diff_html(rd)
        since = ((rd.get("recheck") or {}).get("since")) or "first check"
        if panels["brief"]:
            bottom_parts.append(f'<p class="sec-kicker">What changed since {e(since)}</p>{panels["brief"]}')
        refresh_report_html = panels["report"]
        refresh_appendix_html = panels["appendix"]

    if bottom_parts:
        sec("Bottom line", "".join(bottom_parts), "brief")
    if refresh_appendix_html:
        sec("What changed — full re-check detail", refresh_appendix_html, "appendix")

    charters_html = _lens_charters_html(data.get("lens_charters"))
    frame_html = ""
    if data.get("decision_frame"):
        frame_html = f'<div class="artifact">{_md_block(data["decision_frame"])}</div>'
    council_parts = []
    if frame_html:
        council_parts.append(frame_html)
    if charters_html:
        council_parts.append(
            '<details class="block-detail"><summary>Meet the five lenses</summary>'
            f'{charters_html}</details>'
        )
    if council_parts:
        sec("The question and the council", "".join(council_parts), "report")

    def _attr(cls, label, d):
        persp = e(" + ".join(p.title() for p in d.get("perspectives", []))) if d.get("perspectives") else ""
        note = text_refs(d.get("note", "")) if d.get("note") else ""
        sep = " — " if persp and note else ""
        pb = f"<b>{persp}</b>" if persp else ""
        nn = f'<span class="attr-note">{note}</span>' if note else ""
        return f'<span class="attr {cls}"><span class="attr-label">{label}</span>{pb}{sep}{nn}</span>'

    def _finding_card(f, idx):
        contested = str(f.get("reliability", "")).lower() in ("low", "contested", "weak")
        num = f'<span class="fnum">{idx}</span>'
        kicker = f'<p class="fkicker">{e(f["kicker"])}</p>' if f.get("kicker") else ""
        title = f'<h4 class="ftitle">{e(f["title"])}</h4>' if f.get("title") else ""
        rel, score = f.get("reliability"), f.get("score")
        head = ""
        if rel or score is not None:
            rl = f'<span class="rel-pill">RELIABILITY: {e(str(rel).upper())}</span>' if rel else ""
            sc = f'<span class="rel-score"><b>{e(score)}</b>/10</span>' if score is not None else ""
            head = f'<div class="fhead">{rl}{sc}</div>'
        body = f'<div class="fbody">{text_refs(f.get("text",""))}{refs(f.get("claims"))}</div>'
        attrs = ""
        if f.get("supported_by"):
            attrs += _attr("supported", "SUPPORTED BY", f["supported_by"])
        if f.get("challenged_by"):
            attrs += _attr("challenged", "CHALLENGED BY", f["challenged_by"])
        cor = f.get("corrected")
        if cor:
            ctext = cor if isinstance(cor, str) else (cor.get("note", "") if isinstance(cor, dict) else "")
            if ctext:
                attrs += f'<span class="attr corrected"><span class="attr-label">CORRECTED</span>{text_refs(ctext)}</span>'
        attrs_div = f'<div class="finding-attrs">{attrs}</div>' if attrs else ""
        cls = "fcard contested" if contested else "fcard"
        return f'<div class="{cls}">{num}{kicker}{title}{head}{body}{attrs_div}</div>'

    def _finding_score(f):
        try:
            return float(f.get("score"))
        except (TypeError, ValueError):
            return float("-inf")

    fnd = data.get("strongest_findings", [])
    if fnd:
        ranked_findings = sorted(
            enumerate(fnd),
            key=lambda item: (-_finding_score(item[1]), item[0]),
        )
        body = (
            '<div class="findings">'
            + "".join(_finding_card(f, i) for i, (_, f) in enumerate(ranked_findings, 1))
            + "</div>"
        )
        sec("Strongest evidence-backed findings", body, "brief")

    effects_by_claim = _claim_effects_from_deliberation(data.get("deliberation"))
    claims_html = _claims_table_html(data.get("claims"), effects_by_claim)
    if claims_html:
        confidence_kpi = (
            '<div class="kpi-card"><span class="kpi-icon">⚡</span><div>'
            '<b class="kpi-title">Confidence score (0.0–1.0)</b>'
            '<p class="kpi-desc">The number next to the lightning-bolt icon is the lens’s own subjective '
            'strength of belief in that claim &mdash; <b>not a calibrated probability</b>. Nothing in this '
            'workflow back-tests these numbers against outcomes, so <code>0.88</code> means only that the lens '
            'is fairly but not fully certain; it does not mean the claim is right 88&nbsp;% of the time. '
            'Each score carries a <b>basis</b> (the evidence tier, verdict, and full-text status behind it) '
            'shown beside the number &mdash; read the basis, not the digits. It is intentionally '
            '<b>separate from the Status column</b>: a high-confidence forecast is still a forecast, not '
            'evidence. As a rule of thumb, the Stage 6 adversarial review flags confidence ≥ 0.8 on any claim '
            'whose status is not <code>supported</code> as possible overconfidence &mdash; worth a second '
            'look.</p></div></div>'
        )
        sec("Claims & evidence ledger", confidence_kpi + claims_html, "report")

    _sources_by_id = {
        (s.get("id") or s.get("source_id")): s
        for s in (data.get("sources") or [])
        if isinstance(s, dict) and (s.get("id") or s.get("source_id"))
    }
    evidence_html = _evidence_table_html(
        data.get("evidence"), _sources_by_id or None, data.get("evidence_verdicts")
    )
    argument_support_html = _argument_support_html(
        data.get("review") or {}, data.get("support_packets"), data.get("evidence_verdicts"), scores
    )
    if argument_support_html:
        sec("Argument support", argument_support_html, "report")
    if evidence_html:
        sec("Evidence registry", evidence_html, "report")

    # The interactive Cytoscape map (and its ~373 KB inline library) is heavy;
    # keep it in the appendix so brief/report stay lightweight and printable.
    if _layer_visible(layer, "appendix"):
        argmap_html = _argument_map_interactive_html(data.get("argument_map"), data)
        if argmap_html:
            sec("Argument map", argmap_html, "appendix")

    cons = data.get("contradictions", [])
    lens_snapshot = _lens_snapshot_html(data.get("lens_snapshot"))
    cdetail = data.get("contradiction_detail") or {}
    claim_by_id = {(c.get("claim_id") or c.get("id")): c
                   for c in (data.get("claims") or []) if isinstance(c, dict)}
    if cons:
        rows = ""
        for c in cons:
            tcls, tlbl = _CONFLICT.get(str(c.get("status","")).lower(), ("part", c.get("status","")))
            stake = text_refs(c.get("stake", ""))
            # The one-page brief shows only the summary row; the expandable
            # positions/resolution detail belongs to the fuller layers.
            det = cdetail.get(c.get("id"))
            if layer != "brief" and isinstance(det, dict):
                stake += _cx_detail_html(det, claim_by_id)
            # 07c: mirror the contradiction's criticality chip into the Status cell.
            crit_chip = ""
            xdc = det.get("decision_criticality") if isinstance(det, dict) else None
            if isinstance(xdc, dict):
                xcrit = str(xdc.get("criticality") or "").lower()
                if xcrit in ("pivotal", "contributing", "peripheral"):
                    crit_chip = f' <span class="claim-chip claim-crit-{xcrit}">{e(xcrit)}</span>'
            rows += ('<tr id="ref-%s"><td class="mono">%s</td><td><span class="tag kind">%s</span></td>'
                     '<td>%s</td><td><span class="tag %s">%s</span>%s</td></tr>' % (
                         e(c.get("id","")), e(c.get("id","")), e(c.get("kind","")), stake, tcls, e(tlbl), crit_chip))
        body = (lens_snapshot + '<table><thead><tr><th>Conflict</th><th>Kind</th><th>What is at stake</th>'
                '<th>Status</th></tr></thead><tbody>' + rows + "</tbody></table>")
        # 07d brief line: how many still-open disagreements could flip the decision.
        would_flip_n = 0
        for c in cons:
            det = cdetail.get(c.get("id"))
            if not isinstance(det, dict):
                continue
            plan = det.get("resolution_plan")
            if (isinstance(plan, dict)
                    and str(plan.get("decision_impact") or "").lower() == "would_flip"
                    and str(det.get("resolution_status") or "").lower() != "resolved"):
                would_flip_n += 1
        if would_flip_n:
            if would_flip_n == 1:
                body += ('<p class="rp-brief">1 open disagreement could change the decision; '
                         'there is a plan for how to settle it.</p>')
            else:
                body += ('<p class="rp-brief">%d open disagreements could change the decision; '
                         'there are plans for how to settle them.</p>' % would_flip_n)
        sec("Where the lenses disagree", body, "brief")
    elif lens_snapshot:
        sec("Lens posture snapshot", lens_snapshot, "report")

    # 07d: "How to resolve the disagreements that matter" — additive-optional,
    # report tier. Only contradictions carrying a resolution_plan appear, ordered
    # would_flip → might_flip → unlikely_to_change (stable within a tier). A bundle
    # with no resolution_plan anywhere registers no section at all.
    _RP_ORDER = {"would_flip": 0, "might_flip": 1, "unlikely_to_change": 2}
    planned = []
    for i, c in enumerate(cons):
        det = cdetail.get(c.get("id"))
        if isinstance(det, dict) and isinstance(det.get("resolution_plan"), dict):
            planned.append((i, c, det))
    if planned:
        planned.sort(key=lambda t: (
            _RP_ORDER.get(str(t[2]["resolution_plan"].get("decision_impact") or "").lower(), 3),
            t[0]))
        cards = ""
        for _i, c, det in planned:
            xid = c.get("id") or det.get("id") or ""
            plan = det["resolution_plan"]
            impact = str(plan.get("decision_impact") or "").lower()
            muted = " rp-card-muted" if impact == "unlikely_to_change" else ""
            topic = det.get("topic") or c.get("stake") or ""
            head = (f'<div class="rp-head">{refs([xid]).strip()} '
                    f'<span class="rp-topic">{text_refs(topic)}</span></div>')
            cards += f'<div class="rp-card{muted}">{head}{_resolution_plan_inner(plan)}</div>'
        body = ('<p class="rp-intro">These disagreements are still open. Each row is a concrete '
                'way to settle one — the evidence it needs, roughly how much effort, and whether '
                'resolving it could change the recommendation. Ordered by decision impact; the '
                'effort and impact ratings are ordinal judgments, not calculated values.</p>'
                '<div class="rp-list">' + cards + "</div>")
        sec("How to resolve the disagreements that matter", body, "report")

    if data.get("contradiction_ledger"):
        sec("Contradiction ledger notes", f'<div class="artifact">{_md_block(data["contradiction_ledger"])}</div>', "appendix")

    delib_html = _deliberation_html(data.get("deliberation"))
    if delib_html:
        sec("Council deliberation", delib_html, "appendix")

    opts = data.get("options", [])
    if opts:
        body = ""
        tripwires = data.get("decision_tripwires") if isinstance(data.get("decision_tripwires"), list) else []
        for o in opts:
            ccls, clbl = _STRENGTH.get(str(o.get("strength","")).lower(), ("s-none", o.get("strength","")))
            pts = "".join(f"<li>{text_refs(x)}</li>" for x in o.get("points", []))
            when = f'<p class="when">When appropriate: {text_refs(o["when"])}</p>' if o.get("when") else ""
            linked_tw = [
                tw for tw in tripwires
                if isinstance(tw, dict) and tw.get("option") == o.get("name")
            ]
            revisit = ""
            if linked_tw:
                items = "".join(
                    '<li>%s %s</li>' % (
                        _tripwire_anchor(tw.get("id")),
                        text_refs(tw.get("condition", "")))
                    for tw in sorted(linked_tw, key=_tripwire_sort_key)
                )
                revisit = f'<div class="opt-trips"><b>Revisit if</b><ul>{items}</ul></div>'
            body += ('<div class="opt"><span class="chip %s">%s</span><h4>%s</h4><ul>%s</ul>%s%s</div>' % (
                ccls, e(clbl), e(o.get("name","")), pts, when, revisit))
        sec("Decision options & trade-offs", body, "brief")

    tripwires_html = _tripwires_html(data.get("decision_tripwires"))
    if tripwires_html:
        sec("Revisit this decision if…", tripwires_html, "brief")

    acts = data.get("next_actions", [])
    if acts:
        body = '<ul class="clean">' + "".join(
            f'<li>{text_refs(x.get("text",""))}{refs(x.get("refs"))}</li>' for x in acts) + "</ul>"
        sec("Recommended next actions", body, "brief")

    gaps = data.get("gaps", [])
    if gaps:
        body = '<ul class="clean">' + "".join(
            f'<li>{text_refs(g.get("text",""))}{refs(g.get("refs"))}</li>' for g in gaps) + "</ul>"
        sec("Evidence gaps & frontier questions", body, "brief")

    if data.get("source_mapped_synthesis"):
        sec("Source-mapped synthesis notes", f'<div class="artifact">{_md_block(data["source_mapped_synthesis"])}</div>', "appendix")

    if data.get("decision_brief"):
        sec("Decision brief artifact", f'<div class="artifact">{_md_block(data["decision_brief"])}</div>', "appendix")

    if data.get("evidence_plan"):
        sec("Evidence plan", _evidence_plan_html(data["evidence_plan"]), "appendix")

    srcs = data.get("sources", [])
    if srcs:
        bib_entries = _parse_bibtex(data.get("source_bibtex") or "")
        items = ""
        for s in srcs:
            sid = s.get("id", "")
            url = s.get("url")
            bib = bib_entries.get(sid)
            if bib:
                display = _format_apa_html(bib, url or "")
                if s.get("synthetic"):
                    display = f'<span class="syn">{display}</span>'
            else:
                label = e(s.get("title", ""))
                if url and not s.get("synthetic"):
                    label = f'<a class="slink" href="{e(url)}" target="_blank" rel="noopener">{label}</a>'
                display = f'<span class="syn">{label}</span>' if s.get("synthetic") else label
            note = f'<span class="note">{text_refs(s["note"])}</span>' if s.get("note") else ""
            meta_bits = []
            for label_name, key in (
                ("Authors", "authors"),
                ("Year", "year"),
                ("Venue", "venue"),
                ("Publisher", "publisher"),
                ("Published", "publication_date"),
                ("Accessed", "accessed_at"),
                ("DOI", "doi"),
                ("arXiv", "arxiv_id"),
                ("Publication status", "publication_status"),
                ("Full text", "full_text_status"),
                ("Credibility", "credibility_notes"),
                ("Relevance", "relevance_notes"),
            ):
                val = s.get(key)
                if val and str(val).lower() != "null":
                    if key in ("publication_date", "accessed_at"):
                        val_html = _fmt_datetime_html(str(val))
                    else:
                        val_html = text_refs(val)
                    meta_bits.append(f"<span>{label_name}: {val_html}</span>")
            source_meta = f'<span class="source-meta">{"".join(meta_bits)}</span>' if meta_bits else ""
            identity = " ".join(b for b in (_source_class_badges(s), _source_identity_badges(s)) if b)
            identity_html = (" " + identity) if identity else ""
            items += ('<li id="ref-%s"><span class="sid">%s</span> %s <span class="ty">· %s</span>%s%s</li>' % (
                e(sid), e(sid), display, e(s.get("type", "")), identity_html, note + source_meta))
        source_body = '<ul class="src">' + items + "</ul>"
        if data.get("source_bibtex"):
            source_body += (
                '<details class="bibtex-detail"><summary>BibTeX records</summary>'
                f'<pre>{e(data["source_bibtex"])}</pre></details>'
            )
        sec("Sources", source_body, "report")

    manifest_html = _run_manifest_html(data.get("run_manifest"))
    if manifest_html:
        sec("Run manifest", manifest_html, "appendix")

    provenance_html = _provenance_html(data.get("provenance"))
    if provenance_html:
        sec("Provenance & integrity", provenance_html, "appendix")

    if data.get("adversarial_review"):
        sec("Adversarial review notes", f'<div class="artifact">{_md_block(data["adversarial_review"])}</div>', "appendix")

    rev = data.get("review", {})
    review_parts = []
    if rev:
        chips = ""
        if scores:
            for k, lbl in (("coverage","coverage"),("traceability","traceability"),
                           ("argument_support","argument-support"),
                           ("contradiction","contradiction-handling"),("recommendation","recommendation-support")):
                if k in scores:
                    chips += f'<span class="score">{lbl} <b>{e(scores[k])}</b></span>'
        issues = ""
        for label, key in (("Blocking","blocking"),("Major","major"),("Minor","minor")):
            vals = rev.get(key) or []
            if vals:
                issues += f'<p class="lead"><b>{label}:</b></p><ul class="clean">' + \
                    "".join(f"<li>{text_refs(v)}</li>" for v in vals) + "</ul>"
        verdict = rev.get("verdict", "")
        summary = (
            f'<p class="lead">{text_refs(rev["summary"])}</p>'
            if rev.get("summary") else ""
        )
        body = (f'<div class="scores">{chips}</div>'
                f'<p class="lead">Verdict <b>{e(verdict)}</b>.</p>{summary}{issues}')
        review_parts.append(body)
    if layer != "brief" and refresh_report_html:
        review_parts.append(
            '<p class="sec-kicker">Claim &amp; contradiction effects</p>' + refresh_report_html
        )
    if review_parts:
        audit_items = []
        if data.get("run_manifest"):
            audit_items.append("run manifest")
        if provenance_html:
            audit_items.append("provenance & integrity")
        if data.get("adversarial_review"):
            audit_items.append("adversarial review notes")
        if refresh_appendix_html:
            audit_items.append("full re-check detail")
        if audit_items:
            review_parts.append(
                '<p class="lead">Audit trail material in the appendix: '
                + e(", ".join(audit_items))
                + '.</p>'
            )
        sec("How this brief was checked", "".join(review_parts), "brief")

    a('<footer><p><b>Storm Council</b> is inspired by research-first knowledge-curation systems, '
      'especially Stanford OVAL\'s STORM line of work. For context, see '
      '<a href="https://oval.cs.stanford.edu/">Stanford OVAL</a>, '
      '<a href="https://storm.genie.stanford.edu/">the public STORM research preview</a>, '
      '<a href="https://storm-project.stanford.edu/research/storm/">the Stanford STORM research page</a>, '
      'and the <a href="https://github.com/stanford-oval/storm">stanford-oval/storm open-source repository</a>. '
      'Storm Council is independently developed and is <b>not</b> affiliated with, endorsed by, '
      'or derived from Stanford University, Stanford OVAL, or the STORM project.</p>'
      '<p>This brief supports research and deliberation. It does not replace domain expertise, '
      'source verification, or accountable human decision-making.</p></footer>')
    a("</main>")

    if len(toc_items) > 1:
        links = "".join(
            f'<li><a href="#sec-{num}"><span class="tn">{num}</span><span>{e(title)}</span></a></li>'
            for num, title in toc_items
        )
        a(f'<nav class="toc" aria-label="Report contents"><h4>Contents</h4><ol>{links}</ol></nav>')
        # Inline, self-contained scroll-spy (no network). The anchor links work
        # without it; this only adds the active-section highlight.
        a('<script>(function(){var L=[].slice.call(document.querySelectorAll(".toc a")),'
          'S=[].slice.call(document.querySelectorAll("section[id]")),m={};'
          'L.forEach(function(a){m[a.getAttribute("href").slice(1)]=a;});'
          'function u(){var c=null;S.forEach(function(s){'
          'if(s.getBoundingClientRect().top<=120)c=s.id;});'
          'L.forEach(function(a){a.classList.remove("active");});'
          'if(c&&m[c])m[c].classList.add("active");}'
          'document.addEventListener("scroll",u,{passive:true});'
          'window.addEventListener("resize",u);u();})();</script>')

    a('<script>(function(){function o(h){if(!h)return;var id=h.charAt(0)==="#"?h.slice(1):h;'
      'try{id=decodeURIComponent(id);}catch(e){}'
      'var t=document.getElementById(id);if(!t)return;'
      'var p=t.parentElement;while(p){if(p.tagName&&p.tagName.toLowerCase()==="details")p.open=true;p=p.parentElement;}'
      'if(!t.hasAttribute("tabindex"))t.setAttribute("tabindex","-1");'
      't.scrollIntoView({block:"start"});'
      'try{t.focus({preventScroll:true});}catch(e){t.focus();}}'
      'document.addEventListener("click",function(ev){var a=ev.target.closest?ev.target.closest("a[href^=\\"#ref-\\"]"):null;'
      'if(a){setTimeout(function(){o(a.getAttribute("href"));},0);}});'
      'window.addEventListener("hashchange",function(){o(location.hash);});'
      'if(location.hash)setTimeout(function(){o(location.hash);},0);})();</script>')

    a('<script>(function(){document.querySelectorAll("time.ts-local").forEach(function(el){'
      'var d=new Date(el.dataset.ts);if(!isNaN(d.getTime())){'
      'el.textContent=d.toLocaleString(undefined,{year:"numeric",month:"short",day:"numeric",'
      'hour:"2-digit",minute:"2-digit",timeZoneName:"short"});}});})();</script>')
    a("</body>\n</html>\n")
    return "\n".join(p)


def _enrich_source_urls(data: dict, base: Path) -> None:
    """Fill missing source metadata from a sibling 03_source_registry.csv."""
    srcs = data.get("sources")
    if not srcs:
        return
    reg = base / "03_source_registry.csv"
    if not reg.exists():
        return
    row_by_id = {}
    with reg.open(newline="", encoding="utf-8") as fh:
        for row in csv.DictReader(fh):
            sid = (row.get("source_id") or "").strip()
            if sid:
                row_by_id[sid] = row
    for s in srcs:
        row = row_by_id.get(s.get("id", ""))
        if not row:
            continue
        if not s.get("url"):
            u = (row.get("url") or "").strip()
            if u:
                s["url"] = u
        if not s.get("type"):
            ty = (row.get("source_type") or "").strip()
            if ty and ty.lower() != "null":
                s["type"] = ty
        for key in (
            "authors", "year", "venue", "doi", "arxiv_id", "publication_status",
            "full_text_status", "source_class", "publisher", "publication_date",
            "accessed_at", "credibility_notes", "relevance_notes",
        ):
            val = (row.get(key) or "").strip()
            if val and val.lower() != "null" and not s.get(key):
                s[key] = val


def _read_jsonl(path: Path) -> list:
    rows: list = []
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            rows.append(json.loads(line))
        except ValueError:
            continue
    return rows


def _fold_in_artifacts(data: dict, base: Path, layer: str = "all") -> None:
    """Read sibling stage artifacts from the report's directory and fold them
    into ``data`` so the report stays complete even when report_data.json is a
    summary. Anything the summary already carries wins; anything absent degrades
    to nothing rendered. Pure local file reads — no network.

    Structured data (claims, evidence, deliberation, manifest, …) is always
    folded because it can feed report/brief sections. The bulky raw-markdown
    stage dumps and the Mermaid/evidence-plan payloads only render in the
    appendix, so they are folded solely for ``appendix``/``all`` — this is what
    keeps the brief and standard report free of duplicated raw artifacts."""
    want_appendix = layer in ("appendix", "all")
    if not data.get("lens_charters"):
        f = base / "02_perspective_scan.json"
        if f.exists():
            try:
                parsed = json.loads(f.read_text(encoding="utf-8"))
            except ValueError:
                parsed = None
            if isinstance(parsed, list):
                data["lens_charters"] = parsed
            elif isinstance(parsed, dict) and isinstance(parsed.get("lenses"), list):
                data["lens_charters"] = parsed["lenses"]

    if not data.get("decision_frame"):
        f = base / "01_decision_frame.md"
        if f.exists():
            data["decision_frame"] = f.read_text(encoding="utf-8")

    # BibTeX feeds the report-tier Sources section (APA formatting), so it is
    # folded for every layer; the remaining raw stage-markdown dumps are appendix-only.
    if not data.get("source_bibtex"):
        f = base / "03_sources.bib"
        if f.exists():
            data["source_bibtex"] = f.read_text(encoding="utf-8")

    if want_appendix:
        for key, filename in (
            ("contradiction_ledger", "04_contradiction_ledger.md"),
            ("source_mapped_synthesis", "05_synthesis.md"),
            ("decision_brief", "05_decision_brief.md"),
            ("adversarial_review", "06_adversarial_review.md"),
        ):
            if not data.get(key):
                f = base / filename
                if f.exists():
                    data[key] = f.read_text(encoding="utf-8")

    if not data.get("claims"):
        f = base / "03_claims.jsonl"
        if f.exists():
            claims = _read_jsonl(f)
            if claims:
                data["claims"] = claims

    if not data.get("evidence"):
        f = base / "03_evidence.jsonl"
        if f.exists():
            evidence = _read_jsonl(f)
            if evidence:
                data["evidence"] = evidence

    if not data.get("support_packets"):
        f = base / "03_support_packets.jsonl"
        if f.exists():
            packets = _read_jsonl(f)
            if packets:
                data["support_packets"] = packets

    if not data.get("evidence_verdicts"):
        f = base / "03_evidence_verdicts.jsonl"
        if f.exists():
            verdicts = _read_jsonl(f)
            if verdicts:
                data["evidence_verdicts"] = verdicts

    if want_appendix and not data.get("argument_map"):
        f = base / "05_argument_map.mmd"
        if f.exists():
            data["argument_map"] = f.read_text(encoding="utf-8")

    if not data.get("deliberation"):
        f = base / "04_council_deliberation.jsonl"
        if f.exists():
            moves = _read_jsonl(f)
            if moves:
                data["deliberation"] = moves

    if not data.get("contradiction_detail"):
        f = base / "04_contradictions.json"
        if f.exists():
            try:
                arr = json.loads(f.read_text(encoding="utf-8"))
            except ValueError:
                arr = None
            if isinstance(arr, list):
                # Canonical id is `id`; `conflict_id`/`contradiction_id` remain
                # as one-release deprecated aliases.
                data["contradiction_detail"] = {
                    (x.get("id") or x.get("conflict_id") or x.get("contradiction_id")): x
                    for x in arr
                    if isinstance(x, dict) and (x.get("id") or x.get("conflict_id") or x.get("contradiction_id"))
                }

    if not data.get("run_manifest"):
        f = base / "run_manifest.json"
        if f.exists():
            try:
                manifest = json.loads(f.read_text(encoding="utf-8"))
            except ValueError:
                manifest = None
            if isinstance(manifest, dict):
                data["run_manifest"] = manifest

    if not data.get("decision_tripwires"):
        f = base / "decision_tripwires.json"
        if f.exists():
            try:
                tripwires = json.loads(f.read_text(encoding="utf-8"))
            except ValueError:
                tripwires = None
            if isinstance(tripwires, list):
                data["decision_tripwires"] = tripwires

    if not data.get("provenance"):
        f = base / "provenance_manifest.json"
        if f.exists():
            try:
                manifest = json.loads(f.read_text(encoding="utf-8"))
            except ValueError:
                manifest = None
            if isinstance(manifest, dict):
                data["provenance"] = manifest

    # 07b: fold the living-brief re-check diff when present (additive-optional —
    # a bundle without refresh_diff.json renders exactly as before).
    if not data.get("refresh_diff"):
        f = base / "refresh_diff.json"
        if f.exists():
            try:
                diff = json.loads(f.read_text(encoding="utf-8"))
            except ValueError:
                diff = None
            if isinstance(diff, dict):
                data["refresh_diff"] = diff

    # 07c: fold the decision-criticality ranking when present (additive-optional —
    # a bundle without decision_criticality.json renders exactly as before). Not
    # appendix-gated: the pivotal brief sentence lives in the brief tier.
    if not data.get("decision_criticality"):
        f = base / "decision_criticality.json"
        if f.exists():
            try:
                dcx = json.loads(f.read_text(encoding="utf-8"))
            except ValueError:
                dcx = None
            if isinstance(dcx, dict):
                data["decision_criticality"] = dcx

    if want_appendix and not data.get("evidence_plan"):
        f = base / "03_evidence_plan.md"
        if f.exists():
            data["evidence_plan"] = f.read_text(encoding="utf-8")

    if not data.get("quality_gate"):
        f = base / "06_quality_gate.json"
        if f.exists():
            try:
                qgate = json.loads(f.read_text(encoding="utf-8"))
            except ValueError:
                qgate = None
            if isinstance(qgate, dict):
                data["quality_gate"] = qgate
                if qgate.get("review_summary"):
                    review = data.setdefault("review", {})
                    review.setdefault("summary", qgate["review_summary"])
                    review.setdefault("verdict", qgate.get("status"))
                    review.setdefault("argument_support_status", qgate.get("argument_support_status"))
                    review.setdefault("scores", {
                        "coverage": qgate.get("coverage_score"),
                        "traceability": qgate.get("traceability_score"),
                        "argument_support": qgate.get("argument_support_score"),
                        "contradiction": qgate.get("contradiction_handling_score"),
                        "recommendation": qgate.get("recommendation_support_score"),
                    })

    f = base / "source_versions.jsonl"
    if f.exists():
        versions = {
            row.get("source_id"): row
            for row in _read_jsonl(f)
            if isinstance(row, dict) and row.get("source_id")
        }
        if versions and data.get("sources"):
            for src in data.get("sources") or []:
                sid = src.get("id") or src.get("source_id")
                version = versions.get(sid)
                if not version:
                    continue
                for key in ("identifiers", "publication_identity", "flags",
                            "canonical_source_id", "duplicate_of"):
                    if key in version and not src.get(key):
                        src[key] = version[key]


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description="Render a Storm Council report (JSON -> HTML).")
    ap.add_argument("input", help="report_data.json")
    ap.add_argument("-o", "--output", default="storm_council_report.html")
    ap.add_argument("--layer", choices=_LAYERS, default="all",
                    help="which layer to render: brief (1-page decision), report "
                         "(brief + analysis), appendix (raw artifacts + interactive "
                         "map + manifest), or all (default; single combined file)")
    args = ap.parse_args(argv)
    data = json.loads(Path(args.input).read_text(encoding="utf-8"))
    base = Path(args.input).parent
    _enrich_source_urls(data, base)
    _fold_in_artifacts(data, base, args.layer)
    Path(args.output).write_text(build(data, args.layer), encoding="utf-8")
    print(f"wrote {args.output} (layer={args.layer})")
    return 0
